# Generated by Django 5.2.7 on 2025-10-18 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('code_sub', models.CharField(auto_created=True, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscritions',
            name='client',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='descritions',
            new_name='descriptions',
        ),
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.AlterField(
            model_name='events',
            name='vagas',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.events'),
        ),
        migrations.DeleteModel(
            name='Inscritions',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(to='core.categoryevent'),
        ),
    ]
