# Generated by Django 5.2.7 on 2025-10-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscribe_remove_inscritions_client_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='code_sub',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
