# Generated by Django 5.2.7 on 2025-10-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoryevent_created_at_categoryevent_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
