# Generated by Django 5.2.7 on 2026-04-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscribe_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='local',
            field=models.CharField(max_length=100),
        ),
    ]
