# Generated by Django 5.2.7 on 2026-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_events_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(blank=True, to='core.categoryevent'),
        ),
    ]
